import {
  Award,
  BarChart3,
  BookOpen,
  Bot,
  Brain,
  Clock,
  Code,
  Cpu,
  Database,
  GitBranch,
  GraduationCap,
  Music,
  Network,
  Phone,
  Server,
  TrendingUp,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/data/types";

export const icons: Record<IconName, LucideIcon> = {
  code: Code,
  server: Server,
  database: Database,
  gitBranch: GitBranch,
  cpu: Cpu,
  bot: Bot,
  trendingUp: TrendingUp,
  music: Music,
  phone: Phone,
  clock: Clock,
  network: Network,
  award: Award,
  bookOpen: BookOpen,
  brain: Brain,
  barChart: BarChart3,
  graduationCap: GraduationCap,
};
